import os

path = r'd:\code\projects\active\FilePilot\frontend\src\app\history\page.tsx'
with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

def replace_lines(start_1_idx, end_1_idx, new_lines_list):
    # start_1_idx and end_1_idx are 1-indexed (like view_file)
    lines[start_1_idx-1:end_1_idx] = [l + '\n' if not l.endswith('\n') else l for l in new_lines_list]

# 1. Header (229-253)
replace_lines(229, 253, [
    '          <div className="px-5 py-5">',
    '            <div className="space-y-4">',
    '              <div className="space-y-1.5 px-1">',
    '                <div className="inline-flex items-center gap-1.5 text-[10px] font-black uppercase tracking-[0.15em] text-primary/45">',
    '                  <PanelLeft className="h-3 w-3" />',
    '                  WORKSPACE',
    '                </div>',
    '                <h1 className="text-[15px] font-black tracking-tight text-on-surface">',
    '                  整理历史记录',
    '                </h1>',
    '              </div>',
    '              ',
    '              <div className="flex divide-x divide-on-surface/8 px-1">',
    '                {historyStats.map((item, idx) => (',
    '                  <div key={item.label} className={cn(',
    '                    "flex-1 space-y-0.5",',
    '                    idx === 0 ? "pr-3" : idx === 1 ? "px-3" : "pl-3"',
    '                  )}>',
    '                    <div className="text-[9px] font-bold uppercase tracking-wider text-ui-muted opacity-60">{item.label}</div>',
    '                    <div className="text-[14px] font-black tabular-nums text-on-surface leading-tight">{item.value}</div>',
    '                  </div>',
    '                ))}',
    '              </div>',
    '            </div>',
    '          </div>'
])

# 2. Filters (255-290)
replace_lines(255, 290, [
    '          <div className="px-5 py-2">',
    '            <div className="space-y-3">',
    '              <div className="relative">',
    '                <Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-ui-muted opacity-50" />',
    '                <input',
    '                  value={query}',
    '                  onChange={(event) => setQuery(event.target.value)}',
    '                  placeholder="搜索记录 ID 或路径..."',
    '                  className="w-full rounded-[6px] border border-on-surface/10 bg-on-surface/[0.02] py-2 pl-[2.25rem] pr-4 text-[12.5px] font-medium text-on-surface outline-none transition-all placeholder:text-ui-muted/50 focus:bg-surface focus:ring-2 focus:ring-primary/5"',
    '                />',
    '              </div>',
    '',
    '              <div className="flex flex-wrap gap-1.5">',
    '                {[',
    '                  { id: "all", label: "全部" },',
    '                  { id: "active", label: "进行中" },',
    '                  { id: "completed", label: "已完成" },',
    '                  { id: "rolled_back", label: "已回退" },',
    '                ].map((item) => (',
    '                  <button',
    '                    key={item.id}',
    '                    type="button"',
    '                    onClick={() => setFilter(item.id as typeof filter)}',
    '                    className={cn(',
    '                      "rounded-full px-3 py-1 text-[11px] font-bold tracking-tight transition-all",',
    '                      filter === item.id',
    '                        ? "bg-primary text-white shadow-sm"',
    '                        : "bg-on-surface/[0.04] text-ui-muted hover:bg-on-surface/[0.08] hover:text-on-surface",',
    '                    )}',
    '                  >',
    '                    {item.label}',
    '                  </button>',
    '                ))}',
    '              </div>',
    '            </div>',
    '          </div>'
])

# 3. List Items (298-443)
replace_lines(298, 443, [
    '          <div className="relative flex-1 overflow-y-auto px-2 py-4 scrollbar-thin">',
    '            {loading ? (',
    '              <div className="flex h-full flex-col items-center justify-center gap-3 opacity-30">',
    '                <Activity className="h-6 w-6 animate-spin text-primary" />',
    '                <p className="text-[12px] font-bold">载入中...</p>',
    '              </div>',
    '            ) : filteredHistory.length > 0 ? (',
    '              <div className="space-y-0.5">',
    '                {filteredHistory.map((entry, idx) => {',
    '                  const active = selectedSessionId === entry.execution_id;',
    '                  const sessionLike = isHistorySessionEntry(entry);',
    '',
    '                  return (',
    '                    <motion.div',
    '                      key={entry.execution_id}',
    '                      initial={{ opacity: 0, x: -8 }}',
    '                      animate={{ opacity: 1, x: 0 }}',
    '                      transition={{ delay: idx * 0.02, duration: 0.3 }}',
    '                      whileTap={{ scale: 0.985 }}',
    '                      role="button"',
    '                      tabIndex={0}',
    '                      onClick={() => setSelectedSessionId(entry.execution_id)}',
    '                      onKeyDown={(event) => {',
    '                        if (event.key === "Enter" || event.key === " ") {',
    '                          event.preventDefault();',
    '                          setSelectedSessionId(entry.execution_id);',
    '                        }',
    '                      }}',
    '                      className={cn(',
    '                        "group relative flex cursor-pointer flex-col gap-0.5 rounded-[6px] px-3 py-2.5 transition-all",',
    '                        active',
    '                          ? "bg-primary/[0.06] shadow-[inset_0_0_0_1px_rgba(14,165,233,0.15)]"',
    '                          : "bg-transparent hover:bg-on-surface/[0.035]",',
    '                      )}',
    '                    >',
    '                      {active && (',
    '                        <motion.div',
    '                          layoutId="history-active-pill"',
    '                          className="absolute left-0 top-2 bottom-2 w-[3px] rounded-r-full bg-primary"',
    '                        />',
    '                      )}',
    '',
    '                      <div className="flex items-center justify-between gap-2">',
    '                        <div className="flex min-w-0 items-center gap-1.5">',
    '                          <span className={cn(',
    '                            "h-1.5 w-1.5 shrink-0 rounded-full",',
    '                            sessionLike ? "bg-primary" : entry.status === "rolled_back" ? "bg-on-surface/30" : "bg-success",',
    '                          )} />',
    '                          <h3 className={cn(',
    '                            "truncate text-[12.5px] font-black tracking-tight",',
    '                            active ? "text-primary" : "text-on-surface/90"',
    '                          )}>',
    '                            {getHistoryEntryName(entry)}',
    '                          </h3>',
    '                        </div>',
    '                        <span className="shrink-0 text-[10px] font-bold text-ui-muted/50">{formatDisplayDate(entry.created_at)}</span>',
    '                      </div>',
    '',
    '                      <div className="flex items-center justify-between gap-2">',
    '                        <p className="truncate text-[10px] font-medium text-ui-muted opacity-60" title={entry.target_dir}>',
    '                          {formatPath(entry.target_dir)}',
    '                        </p>',
    '                        <div className="flex items-center gap-1.5 shrink-0">',
    '                          <span className={cn(',
    '                            "rounded-[3px] px-1 py-0.5 text-[8.5px] font-black uppercase tracking-wider",',
    '                            active ? "bg-primary/10 text-primary/80" : "bg-on-surface/[0.05] text-ui-muted/70"',
    '                          )}>',
    '                            {getEntrySummary(entry)}',
    '                          </span>',
    '                        </div>',
    '                      </div>',
    '                    </motion.div>',
    '                  );',
    '                })}',
    '              </div>',
    '            ) : (',
    '              <div className="flex h-full flex-col items-center justify-center px-6 text-center opacity-40">',
    '                <HistoryIcon className="h-8 w-8 opacity-20" />',
    '                <h3 className="mt-4 text-[13px] font-bold">没有发现记录</h3>',
    '              </div>',
    '            )}',
    '          </div>'
])

# 4. Detail Section Shell (Flattening) (Original 448)
replace_lines(448, 448, [
    '        <section className="relative flex min-h-0 flex-1 flex-col overflow-hidden bg-surface">'
])

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(lines)
